{:ok, _} = Swoosh.Adapters.Sandbox.Storage.start_link([])
ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(MusicLibrary.Repo, :manual)
Ecto.Adapters.SQL.Sandbox.mode(MusicLibrary.BackgroundRepo, :manual)
Ecto.Adapters.SQL.Sandbox.mode(MusicLibrary.TelemetryRepo, :auto)
