# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  fluxon-private-repo:
    type: hex-repository
    repo: fluxon
    url: https://repo.fluxonui.com
    auth-key: ${{ secrets.FLUXON_LICENSE_KEY }}
    public-key-fingerprint: ${{ secrets.FLUXON_KEY_FINGERPRINT }}
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - cloud8421
- package-ecosystem: docker-compose
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - cloud8421
- package-ecosystem: mix
  registries: "*"
  insecure-external-code-execution: allow
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - cloud8421
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - cloud8421
  ignore:
  - dependency-name: "live_toast"
- package-ecosystem: npm
  directory: ".pi/extensions/s3-browser"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - cloud8421
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  assignees:
  - cloud8421
