[env]
LAST_FM_USER = 'change-me'
LAST_FM_API_KEY = 'change-me'
OPENAI_KEY = 'change-me'
FLUXON_KEY_FINGERPRINT = 'change-me'
FLUXON_LICENSE_KEY = 'change-me'
DBUI_URL = 'sqlite:data/music_library_dev.db'

[tools]
hurl = 'latest'
sqlite = 'latest'
gh = 'latest'

[task_config]
includes = ["scripts"]

# PRODUCTION

[tasks."prod:test"]
description = 'Run HTTP tests against production'
run = 'hurl --test test/prod.hurl'

# DEVELOPMENT/TEST

[tasks.test]
description = 'Run project tests'
run = 'mix test'

[tasks."dev:readme-preview"]
description = 'Preview the README file via a GH flavoured markdown rendered'
run = 'gh gfm-preview README.md'
