[env]
# BUILD
FLUXON_KEY_FINGERPRINT = 'change-me'
FLUXON_LICENSE_KEY = 'change-me'

# RUNTIME
CLOAK_ENCRYPTION_KEY = 'change-me'
LAST_FM_API_KEY = 'change-me'
LAST_FM_SHARED_SECRET = 'change-me'
LAST_FM_USER = 'change-me'
OPENAI_KEY = 'change-me'
DISCOGS_PERSONAL_ACCESS_TOKEN = 'change-me'

# DEPLOYMENT
HURL_api_token = 'change-me'
HURL_coolify_app_uuid = 'change-me'
HURL_coolify_host = 'https://<fqdn>'
HURL_coolify_token = 'change-me'

[tools]
elixir = "1.20.0-rc.4-otp-28"
erlang = "28.4.2"
node = "24.13.0"
hurl = 'latest'
sqlite = 'latest'
gh = 'latest'
shellcheck = 'latest'
fd = 'latest'
litestream = 'latest'

[task_config]
includes = ["scripts"]

[tasks.test]
depends = ["dev:partitioned-test 1", "dev:partitioned-test 2"]
