dbs:
  - path: /mnt/music-library/music_library_prod.db
    replica:
      type: s3
      name: music_library_prod
      bucket: ffmusiclibrary
      path: prod
      endpoint: https://nbg1.your-objectstorage.com
      sync-interval: 24h
      snapshot-interval: 24h
      retention: 168h # 1 week
