dbs:
  - path: /mnt/music-library/music_library_prod.db
    replica:
      type: s3
      name: music_library_prod
      bucket: ffmusiclibrary
      path: prod
      endpoint: https://nbg1.your-objectstorage.com
      sync-interval: 1m
      retention: 672h # 4 weeks
