#!/usr/bin/env bash

#MISE description="Deploy on production and monitor deployment"
#MISE confirm="Are you sure you want to deploy to production?"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

hurl --test --progress-bar scripts/prod/deploy.hurl
