#!/usr/bin/env bash

#MISE description="Remove locally downloaded production database backups"
#MISE confirm="Are you sure you want to remove all backups?"

set -e

source "$(dirname "$0")/../_helpers.sh"

ensure_working_directory!

rm data/music_library_prod*
