#!/usr/bin/env bash

#MISE description="Run HTTP tests against production"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

hurl --test test/prod.hurl
