[settings]
python.uv_venv_auto = "source"

[tools]
"uv" = "latest"

[tasks.presto]
run = '''
mpremote fs cp main.py :main.py
mpremote reset
'''

[tasks.music_library]
run = '''
mpremote fs cp music_library.py :main.py
mpremote reset
'''

[tasks.poc]
run = '''
mpremote fs cp poc.py :main.py
mpremote reset
'''

[tasks.emulator]
run = 'pimoroni-emulator --device presto main.py'

[tasks.test]
run = 'pytest tests/ -v'
