[tools]
"uv" = "0.11.8"
"pipx:mpremote" = "latest"
"pipx:pimoroni-emulator" = "latest"

[tasks.presto]
run = '''
mpremote fs cp records_on_the_day.py :main.py
mpremote reset
'''
dir = "{{cwd}}"

[tasks.emulator]
run = 'pimoroni-emulator --device presto records_on_the_day.py'
dir = "{{cwd}}"
