[tools]
"uv" = "latest"
"pipx:mpremote" = "latest"
"pipx:pimoroni-emulator" = "latest"

[tasks.presto]
run = '''
mpremote fs cp main.py :main.py
mpremote reset
'''
dir = "{{cwd}}"

[tasks.emulator]
run = 'pimoroni-emulator --device presto main.py'
dir = "{{cwd}}"
