#!/usr/bin/env bash

#MISE description="Run the application attached to an IEx console"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

iex -S mix phx.server
