#!/usr/bin/env bash

#MISE description="Fix translation file conflicts"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

git co --theirs priv/gettext/default.pot

git co --theirs priv/gettext/en/LC_MESSAGES/default.po

mix gettext.extract --merge
