#!/usr/bin/env bash

#MISE description="Run static checks for code formatting, translations, quality"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

mix lint
