#!/usr/bin/env bash

#MISE description="Run static checks for code formatting, translations, quality"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

debug_msg "Formatting..."
mix format

debug_msg "Running credo..."
mix credo

debug_msg "Extracting translations..."
mix gettext.extract --merge

debug_msg "Running shellcheck..."
fd . 'scripts/' --exclude '*.hurl' -t file --exec shellcheck --color
fd . '.claude/hooks' -t file --exec shellcheck --color
