#!/usr/bin/env bash

#MISE description="Show outdated dependencies. Errors at the firsst outdated dependency"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

npm outdated --prefix assets

# shellcheck disable=SC1010
mix do tailwind.check_version, esbuild.check_version, sqlean.check_version

mix hex.outdated --all
