#!/usr/bin/env bash

#MISE description="Render README.md with GitHub Flavored Markdown preview"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

gh gfm-preview README.md
