#!/usr/bin/env bash

#MISE description="Setup the local development environment"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

# Add the Fluxon UI hex source repo

mix hex.repo add fluxon https://repo.fluxonui.com \
  --fetch-public-key $FLUXON_KEY_FINGERPRINT \
  --auth-key $FLUXON_LICENSE_KEY

# Install the gh extension to preview local markdown files

gh extension install thiagokokada/gh-gfm-preview

mix setup
