#!/usr/bin/env bash

#MISE description="Update dependencies. Errors at the firsst outdated dependency"

set -e

source "$(git rev-parse --show-toplevel)/scripts/_helpers.sh"

ensure_working_directory!

npm update --prefix assets

# shellcheck disable=SC1010
mix do tailwind.update_version, esbuild.update_version, sqlean.update_version

mix deps.update --all

mix usage_rules.sync AGENTS.md --all --inline usage_rules:all --link-to-folder deps --remove-missing --yes

gh extension upgrade gfm-preview
