name: Verify
on: workflow_dispatch

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - uses: actions/checkout@v5
      - uses: gacts/install-hurl@v1
      - run: hurl --test --report-tap verification.tap test/prod.hurl
        env:
          HURL_api_token: ${{ secrets.API_TOKEN }}
      - uses: pcolby/tap-summary@v1
