name: Verify
on: workflow_dispatch

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      - uses: gacts/install-hurl@4e426ea8f8626b6f9e87f473751d8a0572370ba3  # v1.3.3
      - run: hurl --test --report-tap verification.tap test/prod.hurl
        env:
          HURL_VARIABLE_api_token: ${{ secrets.API_TOKEN }}
      - uses: pcolby/tap-summary@3f74dc3bad1d527b8c1d5fa88e2f72a3adb2d9e6  # v1.2.0
